import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Providers } from "./providers";
import ThemeInitializer from "@/components/ThemeInitializer";
import PublicChrome from "@/components/PublicChrome";
import { RequestsProvider } from "@/contexts/RequestsContext"; // Import the RequestsProvider
=======
import { Providers } from "@/app/providers";
import ThemeInitializer from "@/components/ThemeInitializer";
import PublicChrome from "@/components/PublicChrome"; // ✅ new
// ❗ fix: no trailing space in the Footer import you had before
>>>>>>> 1829da98d7affe6531aac32dd9c9df11bf0f073d

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "secure systems",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
<<<<<<< HEAD
            try {
              const storedTheme = localStorage.getItem('secure-shield-theme');
              const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              const theme = storedTheme || (prefersDark ? 'dark' : 'dark'); // Force dark
              document.documentElement.classList.toggle('dark', theme === 'dark');
              if (!storedTheme) localStorage.setItem('secure-shield-theme', 'dark');
            } catch (e) {}
          `,
=======
              try {
                const storedTheme = localStorage.getItem('secure-shield-theme');
                const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                const theme = storedTheme || (prefersDark ? 'dark' : 'dark'); // Force dark
                document.documentElement.classList.toggle('dark', theme === 'dark');
                if (!storedTheme) localStorage.setItem('secure-shield-theme', 'dark');
              } catch (e) {}
            `,
>>>>>>> 1829da98d7affe6531aac32dd9c9df11bf0f073d
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeInitializer />
        <Providers>
          <RequestsProvider>
            {" "}
            {/* Wrap with RequestsProvider */}
            <PublicChrome>{children}</PublicChrome>
          </RequestsProvider>
        </Providers>
      </body>
    </html>
  );
}
